# Generated by Django 3.0.6 on 2020-05-19 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0003_swarmphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwarmNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('swarm', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='report.SwarmReport')),
            ],
        ),
    ]
