# Generated by Django 3.0.6 on 2020-05-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swarmuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='swarmuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
