# Generated by Django 3.0.6 on 2020-05-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0002_auto_20200518_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swarmuser',
            name='auth0_profile',
        ),
        migrations.AddField(
            model_name='swarmuser',
            name='zip',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
