# Generated by Django 3.0.6 on 2020-06-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0003_auto_20200526_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='swarmuser',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swarmuser',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
